[versions]
kotlin = "1.9.21"
kotlinxDatetime = "0.5.0"
ksp = "1.9.21-1.0.16"
ktx = "1.12.0"
gradle = "8.2.0"
lifecycle = "2.6.2"
junit = "4.13.2"
coroutines = "1.7.3"
viewmodel-ktx = "2.6.2"
dagger-hilt = "2.48.1"
hilt-compiler = "1.1.0"
timber = "5.0.1"
desugar-jdk-libs = "2.0.4"
compose = "1.5.4"
compose-compiler = "1.5.5-dev-k1.9.21-163bb051fe5"
coil = "2.5.0"
compose-activity = "1.8.1"
compose-paging = "3.2.1"
compose-livedata = "1.5.4"
composeMaterial3 = "1.1.2"
onebone = "2.3.5"
mixpanel = "7.3.2"
firebaseBom = "32.6.0"
qonversion-sdk = "4.2.0"
billing-version = "6.1.0"
accompanist = "0.27.0"
compose-destinations = "1.9.55"
room = "2.6.1"
play-services-auth = "20.7.0"
ktlint = "12.0.3"
google-services = "4.4.0"


play = "2.0.1"
one-tap = "1.0.3"
easycrop = "0.1.1"
paging = "3.2.1"
datastore = "1.0.0"
lottie = "6.1.0"
retrofit = "2.9.0"
arch-core-testing = "2.2.0"
truth = "1.1.5"
leakcanary = "2.10"
searchable-dropdown = "0.2.7"
junit-ext = "1.1.5"
espresso-core = "3.5.1"
horizontal-calendar-view = "1.0.4"
core-splash-screen = "1.0.1"
material = "1.5.4"
appcompat = "1.6.1"
okhttp = "5.0.0-alpha.2"
chucker = "4.0.0"
firebase-auth-ktx = "22.3.0"
firebase-storage-ktx = "20.3.0"
firebase-database-ktx = "20.3.0"
material-icons-extended = "1.5.4"
compose-hilt-navigation = "1.1.0"
spotless = "6.4.2"
android-material = "1.10.0"
#
[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }

viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewmodel-ktx" }

dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger-hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compiler" }

compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons-extended" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }

compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "compose-paging" }
compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose-livedata" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "compose-hilt-navigation" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
toolbar-compose = { module = "me.onebone:toolbar-compose", version.ref = "onebone" }
mixpanel = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel" }
play-review = { group = "com.google.android.play", name = "review", version.ref = "play" }
play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "play" }
play-app-update = { group = "com.google.android.play", name = "app-update", version.ref = "play" }
play-app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "play" }
billing = { group = "com.android.billingclient", name = "billing", version.ref = "billing-version" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }
one-tap-compose = { module = "com.github.stevdza-san:OneTapCompose", version.ref = "one-tap" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebase-storage-ktx" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase-auth-ktx" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebase-database-ktx" }
qonversion-sdk = { group = "io.qonversion.android.sdk", name = "sdk", version.ref = "qonversion-sdk" }
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "arch-core-testing" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
easycrop = { group = "io.github.mr0xf00", name = "easycrop", version.ref = "easycrop" }
searchable-dropdown = { group = "com.github.Breens-Mbaka", name = "Searchable-Dropdown-Menu-Jetpack-Compose", version.ref = "searchable-dropdown" }
junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit-ext" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
compose-destinations-animations = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
horizontal-calendar-view = { module = "com.github.JoelKanyi:HorizontalCalendarView", version.ref = "horizontal-calendar-view" }
core-splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "core-splash-screen" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
accompanist-system-ui-controller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }

[plugins]
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }

